# Generated by Django 4.1.7 on 2023-02-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcode', models.CharField(default=9879593, max_length=10, unique=True)),
                ('quantity', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('sellingcost', models.FloatField(default=0.0)),
                ('buyingcost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=0)),
                ('orderdatetime', models.DateTimeField(auto_now_add=True)),
                ('productcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashapi.shopstore')),
            ],
        ),
    ]
