# Generated by Django 4.1.7 on 2023-02-24 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('sellingcost', models.FloatField(default=0.0)),
                ('buyingcost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=0)),
                ('totalprice', models.FloatField(default=0.0)),
                ('productcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashapi.shopstore')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdatetime', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 2, 25, 8, 10, 22, 794234, tzinfo=datetime.timezone.utc))),
                ('totalprice', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashapi.customer')),
                ('orderproduct', models.ManyToManyField(to='cashapi.orderproduct')),
            ],
        ),
    ]
