# Generated by Django 4.1.7 on 2023-02-22 15:33

import cashapi.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('sellingcost', models.FloatField(default=0.0)),
                ('buyingcost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=0)),
                ('orderdatetime', models.DateTimeField(default=cashapi.models.getDateAndTime)),
                ('totalprice', models.FloatField(default=0.0)),
                ('productcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashapi.shopstore')),
            ],
        ),
    ]
