# Generated by Django 4.1.7 on 2023-02-22 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 15, 59, 51, 822433, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orderdatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
