# Generated by Django 4.1.7 on 2023-02-24 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='totalprice',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='customerorderproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 8, 17, 54, 627653, tzinfo=datetime.timezone.utc)),
        ),
    ]
