# Generated by Django 4.1.7 on 2023-02-24 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapi', '0002_rename_totalprice_orderproduct_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstore',
            name='currentquantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerorderproduct',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 8, 22, 19, 549566, tzinfo=datetime.timezone.utc)),
        ),
    ]
